### ISSUE TITLE
isvalidip introduces a bug

### ISSUE THREAD

**Issue by ibrasec** [ibrasec/easy_antispoof#1]
i have tried to add the subnet 1.1. to be verified by the isvalidip function and it returns an error

>>> from netaddr import IPNetwork
>>> 
>>> 
>>> def isvalidip(ip):
...     '''
...     To check if the passed ip address is a valid ipv4 or ipv6 address
...     example:
...     >>>isvalidip('10.1.1.1')
...     True
...     >>>isvalidip('10.1.1.1.')
...     False
...     >>>isvalidip('2001:db8::1/120')
...     True
...     '''
...     try:
...         IP = IPNetwork(ip.strip())
...         return True
...     except netaddr.core.AddrFormatError:
...         return False
...     except ValueError:
...         return False
... 
>>> 
>>> 
>>> isvalidip('1.1.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 15, in isvalidip
NameError: global name 'netaddr' is not defined

**Comment by ibrasec** [comment]
Thanks for pointing to this issue
The issue has been fixed, i forgot to include
import netaddr.core
